version: '3'
services:
  messages_service:
    build:
      context: ./MessagesService
      dockerfile: Dockerfile
    depends_on:
      db:
        condition: service_healthy
    ports:
      - "8080:8080"

  user_management_service:
    build:
      context: ./UserManagementService
      dockerfile: Dockerfile
    depends_on:
      db:
        condition: service_healthy
    ports:
      - "5001:5001"

  feed_service:
    build:
      context: ./FeedService
      dockerfile: Dockerfile
    depends_on:
      db:
        condition: service_healthy
    ports:
      - "5002:5002"

  db:
    build:
      context: ./Database
      dockerfile: Dockerfile
    environment:
      POSTGRES_USER: ${POSTGRES_USER}
      POSTGRES_PASSWORD: ${POSTGRES_PASSWORD}
      POSTGRES_DB: ${POSTGRES_DB}
    ports:
      - "5433:5432"
    healthcheck:
      test: [ "CMD-SHELL", "pg_isready -U postgres" ]
      interval: 1s
      timeout: 5s
      retries: 5

  cli_ui:
    build:
      context: ./CliUi
      dockerfile: Dockerfile
    depends_on:
      db:
        condition: service_healthy
    environment:
      BASE_URL_MESSAGES: http://messages_service:8080
      BASE_URL_USER_MANAGEMENT: http://user_management_service:5001
      BASE_URL_FEED: http://feed_service:5002
    command: python cli.py
    stdin_open: true
